package com.home.pizzaweb.model.enumType;

public enum IngredientType {
    ANCHOVIES,
    ARTICHOKE,
    BLACK_OLIVES,
    BLUE_CHEESE,
    CALAMARI,
    CAPERS,
    CHEDDAR_CHEESE,
    COCKTAIL_SAUSAGES,
    CRAB_MEAT,
    EGGS,
    FONTINA_CHEESE,
    GOAT_CHEESE,
    GREEN_OLIVES,
    GREEN_PEPPERS,
    HAM,
    MALTESE_SAUSAGE,
    MOZZARELLA_CHEESE,
    MOZZARELLA_DI_BUFALA,
    MUSHROOMS,
    MUSSELS,
    ONION,
    PARMA_HAM,
    PARMESAN_CHEESE,
    PARMESAN_SHAVINGS,
    PEAS,
    PEPERONI,
    RUCOLA,
    SALAMI,
    SHRIMPS,
    SUN_DRIED_TOMATOES,
    SWEET_CORN,
    TOMATO_SAUCE,
    TUNA,
    CLASSIC_DOUGH,
    NEW_YORK_DOUGH,
    NEAPOLITAN_DOUGH,
    SICILIAN_DOUGH,
    TOMATO_SPICY_SAUCE,
    TOMATO_GARLIC_SAUCE;





}